### ISSUE TITLE
Add Members Section

### ISSUE THREAD

**Issue by all3n49** [daabChingrii/website#13]
### Description
Create a **Members Section** on the website to showcase the contributors or team members involved in the project. This section should highlight their roles, photos, and any relevant social media links.

### Requirements
- **Layout**: Each member should be displayed in a card format with the following information:
  - Name
  - Role/Position
  - Profile Picture
  - Links to social media profiles (e.g., GitHub, LinkedIn)
- **Responsiveness**: Ensure the layout adjusts properly for mobile and desktop views.
- **Animations**: Consider adding hover effects or animations to enhance user experience.

### Additional Notes
- Use Tailwind CSS for styling the section.
- You can include a brief description of the team or project's vision above the member cards.

### Labels
- `Hacktoberfest`, `enhancement`, `good first issue`

**Comment by Virtual4087** [comment]
Hey @all3n49 I could do it. Just need to know if I just need to create a layout for the card or include the actual contributor list with details? If it's later part, please let me know where I can find it :)
