### ISSUE TITLE
Add a Feature Section

### ISSUE THREAD

**Issue by all3n49** [daabChingrii/website#15]
### Description
Create a **Features Section** on the website to highlight the key functionalities and benefits of the project. This section should visually present the main features in a clear and engaging manner.

### Requirements
- **Layout**: Each feature should be displayed in a card or grid format, including the following elements:
  - Feature Title
  - Brief Description
  - Icon or Image representing the feature
- **Responsive Design**: Ensure the layout is responsive and looks good on both mobile and desktop devices.
- **Animated Effects**: Consider adding subtle animations or transitions when features are hovered over or when they enter the viewport.

### Additional Notes
- Use Tailwind CSS for styling the section.
- Refer to the Aeternity UI for inspiration: [Aeternity Feature Sections](https://ui.aceternity.com/components/feature-sections).
- Aim for a clean and modern design that aligns with the overall aesthetic of the website.
- You can use placeholder icons or images that can later be replaced with actual assets.

### Labels
- `Hacktoberfest`, `enhancement`, `good first issue`

**Comment by MadhurSaluja** [comment]
@all3n49 if its not done yet, can I work on this?

**Comment by amaan-bhati** [comment]
@MadhurSaluja Sure, feel free to work on it. Assigning it to you

**Comment by MadhurSaluja** [comment]
@amaan-bhati While I was working on It, I wanted to ask somethings:
1. Do you have a list of key functionalities and benefits of the project
2. If No, then should I just write it as Feature 1 , Feature 2

**Comment by MadhurSaluja** [comment]
<img width="1546" alt="Screenshot 2024-12-07 at 11 19 44 PM" src="https://github.com/user-attachments/assets/2e80e37a-e5a4-45ac-adf5-8c1add49bedd">
@amaan-bhati also can u pls provide feedback on this, its just for demo pls let me know if there is something u would like me to change?

**Comment by amaan-bhati** [comment]
> @amaan-bhati While I was working on It, I wanted to ask somethings:
> 
> 1. Do you have a list of key functionalities and benefits of the project
> 2. If No, then should I just write it as Feature 1 , Feature 2

@MadhurSaluja keep it simple, all you need to do is just add a layout for the section, the data for the key functionalities will be overwritten afterwards. As of now, just add some dummy data to the section.

**Comment by amaan-bhati** [comment]
> <img alt="Screenshot 2024-12-07 at 11 19 44 PM" width="1546" src="https://private-user-images.githubusercontent.com/114940822/393562699-2e80e37a-e5a4-45ac-adf5-8c1add49bedd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MzU0MjIsIm5iZiI6MTczMzYzNTEyMiwicGF0aCI6Ii8xMTQ5NDA4MjIvMzkzNTYyNjk5LTJlODBlMzdhLWU1YTQtNDVhYy1hZGY1LThjMWFkZDQ5YmVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQwNTE4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWRiNmE4MzFiY2M2YjhkMTA0MmU3MzIxMzAyNWMwMjRjMmZmOGI0MzIwMjI3Y2VkZGQ2ODg3ODY5NDlkOWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0e5LBJz6XOTLggGnxTeC5gMzrVhds7BoZagjYQUknoE"> @amaan-bhati also can u pls provide feedback on this, its just for demo pls let me know if there is something u would like me to change?

The UI of this component looks nice, you can create a pull request for this component.

**Comment by MadhurSaluja** [comment]
@amaan-bhati can I also preform unit testing for you and update the docx about it aswell?

**Comment by amaan-bhati** [comment]
# Issue Closed

This issue has been successfully resolved with the implementation of the **Features Section** as described in [PR #33](https://github.com/daabChingrii/website/pull/33).

## Summary of Changes
- **Layout**:
  - Created a grid-based format displaying each feature in individual cards.
  - Included key elements such as the feature title, brief description, and an icon/image representing each feature.

- **Responsive Design**:
  - Ensured the section is fully responsive and looks polished on both mobile and desktop devices.

- **Animated Effects**:
  - Added subtle animations for hover interactions and viewport transitions, enhancing visual engagement.

- **Styling**:
  - Used **Tailwind CSS** for a modern and cohesive design aligned with the overall website aesthetic.

- **Inspiration**:
  - Designed based on the **Aeternity Feature Sections** while keeping placeholders for icons/images to be updated with actual assets later.

The section now highlights the key functionalities and benefits of the project in a visually appealing and user-friendly manner.

# Credits: @MadhurSaluja
