### ISSUE TITLE
Add a hero section to the homepage of the website

### ISSUE THREAD

**Issue by amaan-bhati** [daabChingrii/website#3]
# Add Hero Section

### Description
Add a **hero section** to the homepage of the website using **Next.js** and **Tailwind CSS**. The hero section should be visually engaging and fully responsive. Contributors can use any UI libraries (like NextUI, Aeternity, Magic, or Shadcn) to enhance the styling and functionality. 

### Requirements
- **Design**: Create an appealing hero section with a headline, subheading, and a call-to-action (CTA) button.
- **Animation**: Implement animations to make the hero section engaging. You can use a **parallax effect** for the background or apply subtle animations to the text and CTA button.
- **Responsiveness**: Ensure the section is fully responsive on various screen sizes, including mobile, tablet, and desktop.
- **Parallax Effect**: Add a parallax effect to give the section a layered depth on scroll. Use libraries or CSS techniques to achieve this effect.

### Additional Notes
- Feel free to get creative! Any libraries that fit well with Next.js and Tailwind CSS can be used.
- For any animations, prioritize smoothness and compatibility with different devices.
- Make sure to follow the project’s contributing guidelines.

### Acceptance Criteria
- A hero section with a title, subtitle, and CTA button.
- Smooth parallax and animations applied to the background or content.
- Fully responsive across all screen sizes.
- Clear, well-organized code following the project standards.

### Labels
- `Hacktoberfest`
- `enhancement`
- `good first issue`

**Comment by MadhurSaluja** [comment]
@amaan-bhati Hey can u assign this to me?
