### ISSUE TITLE
Add Unit Testing for Key Components

### ISSUE THREAD

**Issue by MadhurSaluja** [daabChingrii/website#34]
# Add Unit Testing for Key Components

## Description

Unit testing for the components in the project has not been implemented yet. To ensure the reliability and functionality of the codebase, I want to write comprehensive unit tests for key components using **Jest** and **React Testing Library**. This will improve code quality, detect potential bugs early, and provide confidence during future development and refactoring.

---

## Scope

I want to create unit tests for the following components:

### **BackgroundGradient**
- Verify children rendering within the gradient container.
- Ensure animation styles are applied conditionally.

### **CardHoverEffect**
- Validate rendering of all card items passed as props.
- Test hover effects for interaction responsiveness.

### **FeaturesSection**
- Test rendering of feature cards.
- Verify responsiveness behaviors.
- Validate proper handling of scenarios like empty feature lists.

**Comment by amaan-bhati** [comment]
# Issue closed
This issue has been resolved with the implementation of unit tests for the specified components in PR #35.
# Summary of Changes:
BackgroundGradient:
Verified children rendering within the gradient container.
Tested conditional application of animation styles.
CardHoverEffect:
Validated rendering of all card items passed as props.
Tested hover effects for interaction responsiveness.
FeaturesSection:
Tested rendering of feature cards.
Verified responsiveness behaviors.
Handled edge cases, such as empty feature lists.
The tests enhance code reliability and ensure these components work as expected, improving the quality and maintainability of the project.

Credits to @MadhurSaluja for the contribution.
